config/routes.rb
Rails.application.routes.draw do
	constraints subdomain: /^(www)$/ do
		scope '(:locale)', locale: /ms|en/ do
			mount ActionCable.server => 'cable'
			root 'home#index'
			namespace :p do
				# PARTICIPANT
				devise_for :participants, path: 'participant_auth', controllers: { 
					registrations: 'participant_auth/registrations',
					sessions: 'participant_auth/sessions'
				}
				authenticated :participant do 
					devise_scope :participant do 
						root to: 'rooms#index', as: 'participant_authenticated' 
					end
				end
				unauthenticated do
					devise_scope :participant do
						root to: 'home#index', as: 'participant_unauthenticated'
					end
				end
				post '/validate', to: 'home#validate_participant', as: 'validate_participant'
				resources :rooms, only: [:index, :show], param: :session_key do
					member do
						post :create_question
						patch :vote
						patch :poll
						post :submit_survey
					end
				end
				root 'rooms#index'
				# PARTICIPANT
			end
			# ADMIN
			scope :admin do
				devise_for :admins, path: 'admins', controllers: { 
					sessions: 'admins/sessions', 
					passwords: 'admins/passwords',
					confirmations: 'admins/confirmations',
					unlocks: 'admins/unlocks'
				}, path_names: {
					sign_in: 'login',
					sign_out: 'logout',
					password: 'secret',
					confirmation: 'verification',
					unlock: 'unblock',
					sign_up: 'logup'
				}
				authenticated :admin do 
					devise_scope :admin do 
						root to: 'dashboard#index', as: 'admin_authenticated' 
					end
				end
				unauthenticated do
					devise_scope :admin do
						root to: 'admins/sessions#new', as: 'admin_unauthenticated'
					end
				end
				resources :admins
				resources :surveys do
					member do
						get :settings
						get :search_question
						post :add_question
						post :create_question
						post :update_question_format
						delete :remove_question
					end
				end
				resources :faq_sets do
					member do
						get :settings
						get :search_question
						post :add_question
						post :create_question
						post :update_question_format
						delete :remove_question
					end
				end
  			resources :questions
				resources :events do
					member do
						get :review
						get :summary
						patch :react, constraints: CommitParamRouting.new(EventsController::SUBMIT), action: :submit
						patch :react, constraints: CommitParamRouting.new(EventsController::APPROVE), action: :approve
						patch :react, constraints: CommitParamRouting.new(EventsController::REJECT), action: :reject
						patch :react, constraints: CommitParamRouting.new(EventsController::CANCEL), action: :cancel
						post :send_invitation
					end
					resources :sessions do
						member do
							get :room
							get :pubroom
							get :settings
							post :add_attachment
							post :add_faq_set
							post :add_survey
							post :update_status
							post :add_poll_item
							post :update_question_status
							patch :import_participants
							delete :remove_attachment
							delete :remove_faq_set
							delete :remove_survey
							delete :remove_poll_item
							get :survey_responses
						end
						resources :polls, path: '/settings/polls', except: [:index, :show]
					end
				end

				#SEARCH
				match 'search' => 'dashboard#search', via: [:get, :post], as: 'search'
			end
			# ADMIN
		end
	end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  	@date = Date.today
  	@years = []
  	@months = []

  	2.times do |i|
  		@years << (@date + i.year).strftime("%Y")
  	end

  	(1..12).each do |i|
  		@months << [Date::MONTHNAMES[i].downcase, i]
  	end


  	if params[:y].present? && !params[:y].blank? && @years.include?(params[:y])
  		@year = params[:y]
  	else
  		@year = @date.strftime("%Y")
  	end

  	if params[:m].present? && !params[:m].blank? && @months.collect{ |m| m[1] }.include?(params[:m].to_i)
  		@month = params[:m]
  		@month_name = Date::MONTHNAMES[params[:m].to_i]
  	else
  		@month = @date.strftime("%m")
  		@month_name = @date.strftime("%B")
  	end

  	@events = if current_admin.em?
  		current_admin.created_events
  	else
  		Event.all
  	end

  	@events = @events.within_month_in_year(@month, @year)
  end

  def search
    @keyword = params[:search][:keyword]

    if @keyword
      @admins     = @keyword.blank? ? [] : Admin.ransack(name_cont: @keyword).result
      @events     = @keyword.blank? ? [] : Event.ransack(title_cont: @keyword).result
      @surveys    = @keyword.blank? ? [] : Survey.ransack(title_cont: @keyword).result
      @faq_sets   = @keyword.blank? ? [] : FaqSet.ransack(title_cont: @keyword).result
      @questions  = @keyword.blank? ? [] : Question.ransack(body_cont: @keyword).result
    end
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<%= page_title t("l.dashboard") %>

<%= content_for :actions do %>
  <div class="actions">
    <div class="btn-group" role="group">
		  <button type="button" class="btn btn-light dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
				<%= @month_name.titleize %>
		  </button>
		  <div class="dropdown-menu dropdown-menu-right" x-placement="bottom-end" style="position: absolute; transform: translate3d(-52px, 33px, 0px); top: 0px; left: 0px; will-change: transform;">
		    <% @months.each do |m| %>
		    	<a href="<%= admin_authenticated_path(m: m[1], y: @year) %>" class="dropdown-item"><%= m[0].titleize %></a>
		    <% end %>
		  </div>
		</div>
		<div class="btn-group" role="group">
		  <button type="button" class="btn btn-light dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
				<%= @year %>
		  </button>
		  <div class="dropdown-menu dropdown-menu-right" x-placement="bottom-end" style="position: absolute; transform: translate3d(-52px, 33px, 0px); top: 0px; left: 0px; will-change: transform;">
		    <% @years.each do |y| %>
		    	<a href="<%= admin_authenticated_path(m: @month, y: y) %>" class="dropdown-item"><%= y %></a>
		    <% end %>
		  </div>
		</div>
  </div>
<% end %>

<div class="clearfix mb-3"></div>

<div class="card widget-pie">
  <div class="col-6 col-sm-4 col-md-6 col-lg-4 widget-pie__item">
    	<span class="event-value"><%= @events.all_pending.count %></span>
  	<div>Pending for approval</div>
  </div>

  <div class="col-6 col-sm-4 col-md-6 col-lg-4 widget-pie__item">
  	<span class="event-value"><%= @events.all_approved.count %></span>
  	<div>Approved events</div>
  </div>

  <div class="col-6 col-sm-4 col-md-6 col-lg-4 widget-pie__item">
  	<span class="event-value"><%= @events.all_rejected.count %></span>
  	<div>Rejected events</div>
  </div>

  <div class="col-6 col-sm-4 col-md-6 col-lg-4 widget-pie__item">
  	<span class="event-value"><%= @events.all_draft.count %></span>
  	<div>Draft</div>
  </div>

  <div class="col-6 col-sm-4 col-md-6 col-lg-4 widget-pie__item">
  	<span class="event-value"><%= @events.all_completed.count %></span>
  	<div>Completed events</div>
  </div>

  <div class="col-6 col-sm-4 col-md-6 col-lg-4 widget-pie__item">
  	<span class="event-value"><%= @events.all_approved.all_today.count %></span>
  	<div>Today's events</div>
  </div>
</div>

app/views/dashboard/search.html.erb
<%= page_title t("l.search_result") %>

<%= content_for :actions do %>
  <div class="actions">
    <%= link_to "", admin_authenticated_path, class: "actions__item zmdi zmdi-arrow-left" %>
  </div>
<% end %>

<% if @admins.any? %>
	<h4 class="pl25"><%= t("l.admin_users") %></h4>

	<div class="listview listview--bordered listview--hover">
	  <% @admins.each do |admin| %>
	  	<a class="listview__item" href="<%= admin_path(admin) %>">
		    <div class="listview__content">
		      <div class="listview__heading"><%= admin.name %></div>
		      <p><%= [admin.staff_id, admin.email, admin.contact_number].reject { |e| e.to_s.empty? }.join(" | ") %></p>
		    </div>
		  </a>
	  <% end %>

	  <div class="clearfix mb-3"></div>
	</div>
<% end %>

<% if @events.any? %>
	<h4 class="pl25"><%= t("l.events") %></h4>

	<div class="listview listview--bordered listview--hover">
	  <% @events.each do |event| %>
	  	<a class="listview__item" href="<%= event_path(event) %>">
		    <div class="listview__content">
		      <div class="listview__heading"><%= event.title %></div>
		      <p><%= [event.date, "#{t('l.sessions')}: #{event.sessions.count}", event.status.humanize].reject { |e| e.to_s.empty? }.join(" | ") %></p>
		    </div>
		  </a>
	  <% end %>

	  <div class="clearfix mb-3"></div>
	</div>
<% end %>

<% if @surveys.any? %>
	<h4 class="pl25"><%= t("l.surveys") %></h4>

	<div class="listview listview--bordered listview--hover">
	  <% @surveys.includes(:creator).each do |survey| %>
	  	<a class="listview__item" href="<%= survey_path(survey) %>">
		    <div class="listview__content">
		      <div class="listview__heading"><%= survey.title %></div>
		      <p><%= [survey.description.truncate(50), survey.creator.name, "#{t('l.questions')}: #{survey.questions.count}"].reject { |e| e.to_s.empty? }.join(" | ") %></p>
		    </div>
		  </a>
	  <% end %>

	  <div class="clearfix mb-3"></div>
	</div>
<% end %>

<% if @faq_sets.any? %>
	<h4 class="pl25"><%= t("l.faq_sets") %></h4>

	<div class="listview listview--bordered listview--hover">
	  <% @faq_sets.includes(:creator).each do |faq_set| %>
	  	<a class="listview__item" href="<%= faq_set_path(faq_set) %>">
		    <div class="listview__content">
		      <div class="listview__heading"><%= faq_set.title %></div>
		      <p><%= [faq_set.description.truncate(50), faq_set.creator.name, "#{t('l.questions')}: #{faq_set.questions.count}"].reject { |e| e.to_s.empty? }.join(" | ") %></p>
		    </div>
		  </a>
	  <% end %>

	  <div class="clearfix mb-3"></div>
	</div>
<% end %>

<% if @questions.any? %>
	<h4 class="pl25"><%= t("l.questions") %></h4>

	<div class="listview listview--bordered listview--hover">
	  <% @questions.includes(:creator).each do |question| %>
	  	<a class="listview__item" href="<%= question_path(question) %>">
		    <div class="listview__content">
		      <div class="listview__heading"><%= question.body %></div>
		      <p><%= [question.origin.humanize, question.creator.name].reject { |e| e.to_s.empty? }.join(" | ") %></p>
		    </div>
		  </a>
	  <% end %>

	  <div class="clearfix mb-3"></div>
	</div>
<% end %>