config/routes.rb
Rails.application.routes.draw do
	constraints subdomain: /^(www)$/ do
		scope '(:locale)', locale: /ms|en/ do
			mount ActionCable.server => 'cable'
			root 'home#index'
			namespace :p do
				# PARTICIPANT
				devise_for :participants, path: 'participant_auth', controllers: { 
					registrations: 'participant_auth/registrations',
					sessions: 'participant_auth/sessions'
				}
				authenticated :participant do 
					devise_scope :participant do 
						root to: 'rooms#index', as: 'participant_authenticated' 
					end
				end
				unauthenticated do
					devise_scope :participant do
						root to: 'home#index', as: 'participant_unauthenticated'
					end
				end
				post '/validate', to: 'home#validate_participant', as: 'validate_participant'
				resources :rooms, only: [:index, :show], param: :session_key do
					member do
						post :create_question
						patch :vote
						patch :poll
						post :submit_survey
					end
				end
				root 'rooms#index'
				# PARTICIPANT
			end
			# ADMIN
			scope :admin do
				devise_for :admins, path: 'admins', controllers: { 
					sessions: 'admins/sessions', 
					passwords: 'admins/passwords',
					confirmations: 'admins/confirmations',
					unlocks: 'admins/unlocks'
				}, path_names: {
					sign_in: 'login',
					sign_out: 'logout',
					password: 'secret',
					confirmation: 'verification',
					unlock: 'unblock',
					sign_up: 'logup'
				}
				authenticated :admin do 
					devise_scope :admin do 
						root to: 'dashboard#index', as: 'admin_authenticated' 
					end
				end
				unauthenticated do
					devise_scope :admin do
						root to: 'admins/sessions#new', as: 'admin_unauthenticated'
					end
				end
				resources :admins
				resources :surveys do
					member do
						get :settings
						get :search_question
						post :add_question
						post :create_question
						post :update_question_format
						delete :remove_question
					end
				end
				resources :faq_sets do
					member do
						get :settings
						get :search_question
						post :add_question
						post :create_question
						post :update_question_format
						delete :remove_question
					end
				end
  			resources :questions
				resources :events do
					member do
						get :review
						get :summary
						patch :react, constraints: CommitParamRouting.new(EventsController::SUBMIT), action: :submit
						patch :react, constraints: CommitParamRouting.new(EventsController::APPROVE), action: :approve
						patch :react, constraints: CommitParamRouting.new(EventsController::REJECT), action: :reject
						patch :react, constraints: CommitParamRouting.new(EventsController::CANCEL), action: :cancel
						post :send_invitation
					end
					resources :sessions do
						member do
							get :room
							get :pubroom
							get :settings
							post :add_attachment
							post :add_faq_set
							post :add_survey
							post :update_status
							post :add_poll_item
							post :update_question_status
							patch :import_participants
							delete :remove_attachment
							delete :remove_faq_set
							delete :remove_survey
							delete :remove_poll_item
							get :survey_responses
						end
						resources :polls, path: '/settings/polls', except: [:index, :show]
					end
				end

				#SEARCH
				match 'search' => 'dashboard#search', via: [:get, :post], as: 'search'
			end
			# ADMIN
		end
	end
end

app/models/event.rb
class Event < ApplicationRecord
	has_paper_trail
	enum status: [:draft, :pending, :approved, :rejected, :cancelled, :completed]
	enum invitation_type: [:normal, :qr]
	has_many :sessions, dependent: :destroy
	has_many :attachments, as: :attachable, dependent: :destroy
	belongs_to :creator, 	class_name: 'Admin'
	belongs_to :assessor,	class_name: 'Admin', optional: true
	accepts_nested_attributes_for :attachments, allow_destroy: true
	validates :title, presence: true
	validates :start_date, presence: true, date: { after_or_equal_to: Date.today }, on: :create
	validates :end_date, presence: true, date: { after_or_equal_to: :start_date }
	validates :invitation_code, presence: true
	scope :all_approved, -> { where(status: :approved) }
	scope :all_pending, -> { where(status: :pending) }
	scope :all_rejected, -> { where(status: :rejected) }
	scope :all_completed, -> { where(status: :completed) }
	scope :all_draft, -> { where(status: :draft) }
	scope :with_session_started, -> { includes(:sessions).where(sessions: { status: :started }) }
	scope :within_month_in_year, -> (m, y) { where('extract(month from start_date) = ? AND extract(year from start_date) = ?', m, y) }
	scope :all_today, -> { where(start_date: Date.today) }

	def date
		start_date.strftime("%d-%m-%Y") + " - " + end_date.strftime("%d-%m-%Y")
	end

	def days
		number_of_days 	= (end_date - start_date).to_i + 1
		days 						= []

		(1..(number_of_days)).each do |day|
			date = (start_date + (day - 1)).strftime("%d-%m-%Y")
			object = [date, day]
			days << object
		end

		return days
	end

	def status_color
		case status
			when "pending"
				"info"
			when "approved"
				"success"
			when "rejected"
				"danger"
			when "cancelled"
				"warning"
			when "completed"
				"purple"
			else
				"secondary"
		end
	end

	def is_ready_to_be_submitted?
		sessions.any? && (draft? || rejected?)
	end

	def is_ready_to_be_assessed?
		pending?
	end

	def as_json(options = {})
    hash										= {}
    hash["id"]							= id
    hash["title"]						= title
    hash["start_date"]			= start_date.strftime("%d-%m-%Y")
    hash["end_date"]				= end_date.strftime("%d-%m-%Y")
    hash["description"]			= description
    hash["invitation_type"]	= invitation_type
    hash["invitation_code"]	= invitation_code
    hash["invitation_code"]	= invitation_code

    if options[:session_id]
    	hash["attachments"]	= attachments.as_json(session_id: options[:session_id])
    else
    	hash["attachments"]	= attachments.as_json
    end

    return hash
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_event, only: [:show, :edit, :update, :destroy, :review, :approve, :reject, :submit, :cancel, :summary, :send_invitation]
  before_action :set_paper_trail_whodunnit
  include Pundit
  after_action :verify_authorized
  after_action :verify_policy_scoped

  # COMMIT PARAMS
  SUBMIT  = I18n.t('l.submit')
  APPROVE = I18n.t('l.approve')
  REJECT  = I18n.t('l.reject')
  CANCEL  = I18n.t('l.cancel')

  def index
    @events = policy_scope(Event)
    @events = @events.includes(:creator).order('created_at DESC').page(params[:page]).per(10)
    authorize @events
  end

  def show
    @sessions = @event.sessions.includes(
      :attachments,
      :polls,
      :participants,
      session_surveys: [:survey],
      session_faq_sets: [:faq_set]
    ).order('day ASC, start_time ASC')
    
    authorize @event
  end

  def review
    @sessions = @event.sessions.includes(
      :attachments,
      :polls,
      :participants,
      session_surveys: [:survey],
      session_faq_sets: [:faq_set]
    ).order('day ASC, start_time ASC')

    authorize @event
  end

  def summary
    @sessions = @event.sessions.includes(
      :attachments,
      :polls,
      :participants,
      session_surveys: [:survey],
      session_faq_sets: [:faq_set]
    ).order('day ASC, start_time ASC')
    
    authorize @event
  end

  def new
    @event = policy_scope(Event).new
    
    if current_admin.huadmin?
      @event = current_admin.created_events.new
    end

    authorize @event
  end

  def edit
    authorize @event
  end

  def create
    @event = policy_scope(Event).new(event_params)
    
    if current_admin.huadmin?
      @event = current_admin.created_events.new(event_params)
    end

    authorize @event

    if @event.save
      redirect_to event_sessions_path(@event), notice: t('msg.created')
    else
      render :new
    end
  end

  def update
    authorize @event

    if @event.update(event_params)
      redirect_to @event, notice: t('msg.updated')
    else
      render :edit
    end
  end

  def destroy
    authorize @event
    @event.destroy
    redirect_to events_url, notice: t('msg.destroyed')
  end

  def approve
    authorize @event
    @event.status = "approved"
    react_responds
  end

  def reject
    authorize @event
    @event.status = "rejected"
    react_responds
  end

  def submit
    authorize @event
    @event.status = "pending"
    react_responds
  end

  def cancel
    authorize @event
    @event.status = "cancelled"
    react_responds
  end

  def send_invitation
    authorize @event

    @event.sessions.each do |session|
      participants = session.participants

      if participants.any?
        participants.each do |participant|
          InvitationMailerJob.perform_later(@event, participant)
        end
      end
    end
    redirect_to @event, notice: t("msg.invitation_sent")
  end

  private
    def set_event
      @event = policy_scope(Event).find(params[:id])
    end

    def event_params
      params.require(:event).permit(policy(Event).permitted_attributes)
    end

    def react_responds
      if (@event.approved? || @event.rejected?) && @event.assessor.nil?
        @event.assessor = current_admin
      end

      if @event.update(permitted_attributes(@event))
        if @event.pending?
          if @event.assessor
            unless @event.assessor == @event.creator
              ActivityMailerJob.perform_later(@event, @event.assessor)
            end
          else
            unless @event.creator.huadmin?
              Admin.all_huadmin.each do |admin|
                ActivityMailerJob.perform_later(@event, @event.creator)
              end
            end
          end
        elsif @event.approved? || @event.rejected?
          ActivityMailerJob.perform_later(@event, @event.creator)
        else
          # DO NOTHING
        end

        redirect_to review_event_path, notice: t('msg.updated')
      else
        render :review
      end
    end
end

app/helpers/events_helper.rb
module EventsHelper
	def event_invitation_types
		Event.invitation_types.map{|k, v|[k.humanize.upcase, k]}
	end
end

app/views/events/_attachment_fields.html.erb
<div class="nested-fields">
	<div class="row">
		<div class="col-md-5">
			<%= f.input :file, label: false %>
			<%= f.hidden_field :file_cache, :value => f.object.file_cache %>
		</div>
		<% if f.object.file? %>
			<div class="col-md-5">
				<%= f.object.file.file.filename %>
			</div>
		<% end %>
		<div class="col-md-2">
			<%= link_to_remove_association f, class: "btn btn-sm btn-danger" do %>
				<i class="zmdi zmdi-close"></i>
			<% end %>
		</div>
	</div>
</div>

app/views/events/_event_details.html.erb
<%= content_for :actions do %>
  <div class="actions">
    <%= link_to "", events_path, class: "actions__item zmdi zmdi-arrow-left", data: tooltip_data(t("l.back")) %>
    <% if policy(event).update? %>
      <%= link_to "", edit_event_path(event), class: "actions__item zmdi zmdi-edit", data: tooltip_data(t("l.edit")) %>
    <% end %>
    <%= link_to "", event_sessions_path(event), class: "actions__item zmdi zmdi-settings", data: tooltip_data(t("l.sessions")) %>
  </div>
<% end %>

<div class="card">
  <div class="card-body">
    <div class="row">
      <div class="col-md-6">
        <div class="row">
          <div class="col-md-12">
            <div class="form-group">
              <strong><%= t('l.title') %></strong><br>
              <%= event.title %>
            </div>
          </div>
          <div class="col-md-12">
            <div class="form-group">
              <strong><%= t('l.date') %></strong><br>
              <%= event.date %> <br>
              <%= "(#{event.days.count} #{t('l.days')})" %>
            </div>
          </div>
          <div class="col-md-12">
            <div class="form-group">
              <strong><%= t('l.description') %></strong><br>
              <%= event.description %>
            </div>
          </div>
          <div class="col-md-12">
            <div class="form-group">
              <strong><%= t('l.invitation_code') %></strong><br>
              <%= event.invitation_code %>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="row">
          <div class="col-md-12">
            <div class="form-group">
              <strong><%= t('l.creator') %></strong><br>
              <%= event.creator.name %>
            </div>
          </div>
          <div class="col-md-12">
            <div class="form-group">
              <strong><%= t('l.creator_remark') %></strong><br>
              <%= event.creator_remark %>
            </div>
          </div>
          <div class="col-md-12">
            <div class="form-group">
              <strong><%= t('l.assessor') %></strong><br>
              <%= event.assessor.nil? ? "N/A" : event.assessor.name %>
            </div>
          </div>
          <div class="col-md-12">
            <div class="form-group">
              <strong><%= t('l.assessor_remark') %></strong><br>
              <%= event.assessor_remark %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <% if act == 'summarize' || act == 'review' %>
      <h4><%= t('l.sessions') %></h4>

      <div class="tab-container">
        <ul class="nav nav-tabs" role="tablist">
          <% @sessions.each_with_index do |s, i| %>
            <li class="nav-item">
              <a class="nav-link <%= 'active show' if i + 1 == 1 %>" data-toggle="tab" href="#eventSession<%= i + 1 %>" role="tab" aria-expanded="false"><%= "#{t('l.session')} #{i + 1}" %></a>
            </li>
          <% end %>
        </ul>

        <div class="tab-content">
          <% @sessions.each_with_index do |s, i| %>
            <div class="tab-pane fade <%= 'active show' if i + 1 == 1 %>" id="eventSession<%= i + 1 %>" role="tabpanel" aria-expanded="false">
              <div class="row">
                <div class="col-md-6">
                  <div class="row">
                    <div class="col-md-12">
                      <div class="form-group">
                        <strong><%= t('l.title') %></strong><br>
                        <%= s.title %>
                      </div>
                    </div>
                    <div class="col-md-12">
                      <div class="form-group">
                        <strong><%= t('l.time') %></strong><br>
                        <%= "#{s.time} | #{s.date.strftime("%d-%m-%Y")}" %>
                      </div>
                    </div>
                    <div class="col-md-12">
                      <div class="form-group">
                        <strong><%= t('l.attachments') %></strong><br>
                        <% if s.attachments.any? %>
                          <% s.attachments.each do |attachment| %>
                            <%= link_to attachment.file.file.filename, attachment.file.url %><br>
                          <% end %>
                        <% else %>
                          N/A
                        <% end %>
                      </div>
                    </div>
                    <div class="col-md-12">
                      <div class="form-group">
                        <strong><%= t('l.faq_sets') %></strong><br>
                        <% if s.session_faq_sets.any? %>
                          <% s.session_faq_sets.each do |sfs| %>
                            <%= link_to sfs.faq_set.title, sfs.faq_set %><br>
                          <% end %>
                        <% else %>
                          N/A
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>

                <div class="col-md-6">
                  <div class="row">
                    <div class="col-md-12">
                      <div class="form-group">
                        <strong><%= t('l.participants') %></strong><br>
                        <%= render 'events/sections/participants', session: s, i: i %>
                      </div>
                    </div>
                    <div class="col-md-12">
                      <div class="form-group">
                        <strong><%= t('l.survey_responses') %></strong><br>
                        
                        <% if s.session_surveys.any? %>
                          <div class="pb-3"></div>
                          <table class="table table-sm mb-0 table-bordered">
                            <thead>
                              <tr>
                                <th><%= t("l.survey") %></th>
                                <th><%= t("l.responses") %></th>
                                <th width="5%"></th>
                              </tr>
                            </thead>
                            <tbody>
                              <% s.session_surveys.each_with_index do |ss, i| %>
                                <tr>
                                  <td>
                                    <a href="#" data-target="#surveysModal<%= ss.id %>" data-toggle="modal">
                                      <%= ss.survey.title %>
                                    </a>
                                    <%= render 'events/sections/surveys', ss: ss %>
                                  </td>
                                  <td><%= ss.participant_surveys.count %></td>
                                  <td>
                                    <% if policy(ss.session).survey_responses? %>
                                      <%= link_to t("l.assess"), survey_responses_event_session_path(event, ss.session.id, ssid: ss.id), class: "btn btn-sm btn-info" %>
                                    <% end %>
                                  </td>  
                                </tr>
                              <% end %>
                            </tbody>
                          </table>
                        <% else %>
                          N/A
                        <% end %>
                      </div>
                    </div>
                    <div class="col-md-12">
                      <div class="form-group">
                        <strong><%= t('l.polls') %></strong><br>
                        
                        <% if s.polls.any? %>
                          <div class="pb-3"></div>
                          <% s.polls.includes(:poll_items).each do |poll| %>
                            <h6 class="mb-3"><%= poll.title %></h6>

                            <ul>
                              <% poll.poll_items.each do |pi| %>
                                <li><%= pi.item %> (<%= pi.votes_for.size %>)</li>
                              <% end %>
                            </ul>

                            <div class="pb-3"></div>
                          <% end %>
                        <% else %>
                          N/A
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>

      <% if act == 'review' %>
        <!-- STATUS UPDATE FORM -->
        <% if policy(event).submit? || policy(event).approve? || policy(event).reject? %>

          <h4><%= t('l.action') %></h4>
          
          <%= simple_form_for event, url: react_event_path(event) do |f| %>
            <% if policy(event).approve? || policy(event).reject? %>
              <%= f.input :assessor_remark %>
            <% end %>
            <% if policy(event).submit? %>
              <%= f.input :creator_remark %>
            <% end %>
            
            <%= hidden_field_tag :_method, :patch %>

            <div class="mt-5 text-center">
              <div class="btn-group">
                <% if policy(event).submit? %>
                  <%= f.button :submit, EventsController::SUBMIT, class: "btn btn-success" %>
                <% end %>
                <% if policy(event).approve? %>
                  <%= f.button :submit, EventsController::APPROVE, class: "btn btn-success" %>
                <% end %>
                <% if policy(event).reject? %>
                  <%= f.button :submit, EventsController::REJECT, class: "btn btn-danger" %>
                <% end %>
              </div>
            </div>
          <% end %>
        <% end %>
        <!-- STATUS UPDATE FORM -->
      <% end %>
    <% end %>
  </div>
</div>

<% if event.versions.any? %>
  <h4 class="mb-3"><%= t('l.logs') %></h4>

  <table class="table table-sm mb-0 table-bordered">
    <thead>
      <tr>
        <th><%= t("l.action") %></th>
        <th><%= t("l.by") %></th>
        <th><%= t("l.time") %></th>
        <th width="50%"><%= t("l.previous") %></th>
      </tr>
    </thead>
    <tbody>
      <% event.versions.each do |v| %>
        <tr>
          <td><%= v.event.humanize %></td>
          <td><%= v.whodunnit ? Admin.find(v.whodunnit.to_i).name : "N/A" %></td>
          <td>
            <%= v.created_at %>
          </td>
          <td>
            <% if v.reify %>
              <code>
                <%= v.reify.attributes.reject!{ |k, v| k == "id" } %>
              </code>
            <% else %>
              N/A
            <% end %>
          </td>  
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/events/_form.html.erb
<%= simple_form_for event do |f| %>
  <%= f.input :title %>
  <div class="row">
    <div class="col-md-6">
      <%= f.input :start_date, as: :string, input_html: { class: "datepicker" } %>
    </div>
    <div class="col-md-6">
      <%= f.input :end_date, as: :string, input_html: { class: "datepicker" } %>
    </div>
  </div>
  <%= f.input :description %>
  <%#= f.input :invitation_type, 
          collection: event_invitation_types, 
          include_blank: t("l.please_select"), 
          input_html: { class: "select2" } %>
  <%= f.input :invitation_code %>

  <h4><%= t('l.related_attachments') %></h4>

  <div id="attachments">
    <%= f.simple_fields_for :attachments do |attachment| %>
      <%= render 'attachment_fields', f: attachment %>
    <% end %>
    <div class="links">
      <%= link_to_add_association t("l.add"), f, :attachments, class: "btn btn-sm btn-primary" %>
    </div>
  </div>

  <div class="mt-5 text-center">
    <%= f.button :submit, t('l.save'), class: "btn btn-light" %>
  </div>
<% end %>

app/views/events/edit.html.erb
<%= page_title "#{t('l.events')} - #{t('l.edit')}" %>

<div class="content__inner">
  <div class="card">
    <div class="card-body">
			<%= render 'form', event: @event, act: 'edit' %>
		</div>
  </div>
</div>

<% content_for :actions do %>
	<div class="actions">
		<%= link_to "", events_path, class: "actions__item zmdi zmdi-arrow-left", data: tooltip_data(t('l.back'))  %>
		<%= link_to "", @event, class: "actions__item zmdi zmdi-search-in-file", data: tooltip_data(t('l.view'))  %>
	</div>
<% end %>

app/views/events/index.html.erb
<%= page_title t('l.events') %>

<%= content_for :actions do %>
  <div class="actions">
    <% if policy(Event).create? %>
      <%= link_to "", new_event_path, class: "actions__item zmdi zmdi-plus", data: tooltip_data(t('l.add_new')) %>
    <% end %>
  </div>
<% end %>

<div class="table-responsive">
  <table class="table table-hover mb-3">
    <thead class="thead-default">
      <tr>
        <th>#</th>
        <th><%= t('l.title') %></th>
        <th><%= t('l.date') %></th>
        <th><%= t('l.status') %></th>
        <th><%= t('l.created_at') %></th>
        <th width="5%"></th>
      </tr>
    </thead>

    <tbody>
      <% policy_scope(@events).each_with_index do |event, i| %>
        <tr>
          <th scope="row"><%= i + 1 %></th>
          <td>
            <% if policy(event).show? %>
              <%= link_to event do %>
                <%= event.title %>
              <% end %>
            <% end %>
          </td>
          <td><%= event.date %></td>
          <td>
            <span class="badge badge-pill badge-<%= event.status_color %>">
              <%= t("l.#{event.status}") %>
            </span>
          </td>
          <td>
            <%= event.created_at.strftime("%d-%m-%Y") %><br>
            <em>
              <%= "#{t('l.created_by')} #{event.creator == current_admin ? t('l.you') : (event.creator.nil? ? '-' : nil_checker(event.creator.name))}" %>
            </em>
          </td>
          <td>
            <div class="btn-group">
              <%= link_to t('l.sessions'), event_sessions_path(event), class: "btn btn-light btn-sm" %>
              <% if policy(event).send_invitation? %>
                <%= link_to t('l.send_invitation'), send_invitation_event_path(event), method: :post, class: "btn btn-primary btn-sm" %>
              <% end %>
              <% if policy(event).review? %>
                <%= link_to t('l.review'), review_event_path(event), class: "btn btn-success btn-sm" %>
              <% end %>
              <% if policy(event).summary? %>
                <%= link_to t('l.summary'), summary_event_path(event), class: "btn btn-info btn-sm" %>
              <% end %>
              <% if policy(event).update? %>
                <%= link_to t('l.edit'), edit_event_path(event), class: "btn btn-secondary btn-sm" %>
              <% end %>
              <% if policy(event).destroy? %>
                <%= link_to t('l.cancel'), event, method: :delete, data: { confirm: t('msg.are_u_sure') }, class: "btn btn-danger btn-sm" %>
              <% end %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= paginate @events %>
</div>

app/views/events/new.html.erb
<%= page_title "#{t('l.events')} - #{t('l.add_new')}" %>

<div class="content__inner">
  <div class="card">
    <div class="card-body">
			<%= render 'form', event: @event, act: 'create' %>
		</div>
  </div>
</div>

<% content_for :actions do %>
	<div class="actions">
		<%= link_to "", events_path, class: "actions__item zmdi zmdi-arrow-left", data: tooltip_data(t("l.back")) %>
	</div>
<% end %>

app/views/events/review.erb
<%= page_title "#{t('l.event_review')} - #{@event.title}" %>

<%= render 'event_details', event: @event, act: 'review' %>

app/views/events/show.html.erb
<%= page_title "#{t('l.events')} - #{@event.title}" %>

<%= render 'event_details', event: @event, act: 'show' %>

app/views/events/summary.html.erb
<%= page_title "#{t('l.event_summary')} - #{@event.title}" %>

<%= render 'event_details', event: @event, act: 'summarize' %>