config/routes.rb
Rails.application.routes.draw do
	constraints subdomain: /^(www)$/ do
		scope '(:locale)', locale: /ms|en/ do
			mount ActionCable.server => 'cable'
			root 'home#index'
			namespace :p do
				# PARTICIPANT
				devise_for :participants, path: 'participant_auth', controllers: { 
					registrations: 'participant_auth/registrations',
					sessions: 'participant_auth/sessions'
				}
				authenticated :participant do 
					devise_scope :participant do 
						root to: 'rooms#index', as: 'participant_authenticated' 
					end
				end
				unauthenticated do
					devise_scope :participant do
						root to: 'home#index', as: 'participant_unauthenticated'
					end
				end
				post '/validate', to: 'home#validate_participant', as: 'validate_participant'
				resources :rooms, only: [:index, :show], param: :session_key do
					member do
						post :create_question
						patch :vote
						patch :poll
						post :submit_survey
					end
				end
				root 'rooms#index'
				# PARTICIPANT
			end
			# ADMIN
			scope :admin do
				devise_for :admins, path: 'admins', controllers: { 
					sessions: 'admins/sessions', 
					passwords: 'admins/passwords',
					confirmations: 'admins/confirmations',
					unlocks: 'admins/unlocks'
				}, path_names: {
					sign_in: 'login',
					sign_out: 'logout',
					password: 'secret',
					confirmation: 'verification',
					unlock: 'unblock',
					sign_up: 'logup'
				}
				authenticated :admin do 
					devise_scope :admin do 
						root to: 'dashboard#index', as: 'admin_authenticated' 
					end
				end
				unauthenticated do
					devise_scope :admin do
						root to: 'admins/sessions#new', as: 'admin_unauthenticated'
					end
				end
				resources :admins
				resources :surveys do
					member do
						get :settings
						get :search_question
						post :add_question
						post :create_question
						post :update_question_format
						delete :remove_question
					end
				end
				resources :faq_sets do
					member do
						get :settings
						get :search_question
						post :add_question
						post :create_question
						post :update_question_format
						delete :remove_question
					end
				end
  			resources :questions
				resources :events do
					member do
						get :review
						get :summary
						patch :react, constraints: CommitParamRouting.new(EventsController::SUBMIT), action: :submit
						patch :react, constraints: CommitParamRouting.new(EventsController::APPROVE), action: :approve
						patch :react, constraints: CommitParamRouting.new(EventsController::REJECT), action: :reject
						patch :react, constraints: CommitParamRouting.new(EventsController::CANCEL), action: :cancel
						post :send_invitation
					end
					resources :sessions do
						member do
							get :room
							get :pubroom
							get :settings
							post :add_attachment
							post :add_faq_set
							post :add_survey
							post :update_status
							post :add_poll_item
							post :update_question_status
							patch :import_participants
							delete :remove_attachment
							delete :remove_faq_set
							delete :remove_survey
							delete :remove_poll_item
							get :survey_responses
						end
						resources :polls, path: '/settings/polls', except: [:index, :show]
					end
				end

				#SEARCH
				match 'search' => 'dashboard#search', via: [:get, :post], as: 'search'
			end
			# ADMIN
		end
	end
end

app/views/layouts/app/_header.html.erb
<header class="header">
	<a class="navigation-trigger hidden-xl-up" href="#" data-sa-action="aside-open" data-sa-target=".sidebar">
  	<i class="zmdi zmdi-menu"></i>
  </a>

  <div class="logo hidden-sm-down">
		<h1>
      <a href="<%= admin_signed_in? ? admin_authenticated_path : p_participant_authenticated_path %>"><i>HandzUp!</i></a>
    </h1>
  </div>

  <% if current_admin %>
    <% unless controller.controller_name == "sessions" && controller.action_name == "pubroom" %>
      <%= simple_form_for :search, url: search_url, html: { class: "search", method: :post }  do |f| %>
        <div class="search__inner">
          <%= f.input_field :keyword, label: false, class: "search__text", placeholder: t('l.search_keyword') %>
          <i class="zmdi zmdi-search search__helper" data-sa-action="search-close"></i>
        </div>
      <% end %>
    <% end %>
  <% end %>

  <ul class="top-nav">
    <!-- <li class="hidden-xl-up"><a href="" data-sa-action="search-open"><i class="zmdi zmdi-search"></i></a></li> -->

    <!-- <li class="dropdown">
      <a href="" data-toggle="dropdown" class="top-nav__notify"><i class="zmdi zmdi-email"></i></a>
      <div class="dropdown-menu dropdown-menu-right dropdown-menu--block">
        <div class="dropdown-header">
            Messages

          <div class="actions">
              <a href="messages.html" class="actions__item zmdi zmdi-plus"></a>
          </div>
        </div>

        <div class="listview listview--hover">
          <a href="" class="listview__item">
            <img src="demo/img/profile-pics/1.jpg" class="listview__img" alt="">

            <div class="listview__content">
              <div class="listview__heading">
                David Belle <small>12:01 PM</small>
              </div>
              <p>Cum sociis natoque penatibus et magnis dis parturient montes</p>
            </div>
          </a>

          <a href="" class="view-more">View all messages</a>
        </div>
      </div>
    </li>

    <li class="dropdown top-nav__notifications">
      <a href="" data-toggle="dropdown" class="top-nav__notify">
      	<i class="zmdi zmdi-notifications"></i>
      </a>
      <div class="dropdown-menu dropdown-menu-right dropdown-menu--block">
        <div class="dropdown-header">
          Notifications

          <div class="actions">
          	<a href="" class="actions__item zmdi zmdi-check-all" data-sa-action="notifications-clear"></a>
          </div>
        </div>

        <div class="listview listview--hover">
          <div class="listview__scroll scrollbar-inner">
            <a href="" class="listview__item">
              <img src="demo/img/profile-pics/1.jpg" class="listview__img" alt="">

              <div class="listview__content">
                <div class="listview__heading">David Belle</div>
                <p>Cum sociis natoque penatibus et magnis dis parturient montes</p>
              </div>
            </a>
          </div>

          <div class="p-1"></div>
        </div>
      </div>
    </li>

    <li class="dropdown hidden-xs-down">
      <a href="" data-toggle="dropdown"><i class="zmdi zmdi-check-circle"></i></a>

      <div class="dropdown-menu dropdown-menu-right dropdown-menu--block" role="menu">
        <div class="dropdown-header">Tasks</div>

        <div class="listview listview--hover">
          <a href="" class="listview__item">
            <div class="listview__content">
              <div class="listview__heading">HTML5 Validation Report</div>

              <div class="progress mt-1">
              	<div class="progress-bar bg-primary w25p" role="progressbar" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </div>
          </a>

          <a href="" class="view-more">View all Tasks</a>
        </div>
      </div>
    </li>

    <li class="dropdown hidden-xs-down">
			<a href="" data-toggle="dropdown"><i class="zmdi zmdi-apps"></i></a>

      <div class="dropdown-menu dropdown-menu-right dropdown-menu--block" role="menu">
        <div class="row app-shortcuts">
          <a class="col-4 app-shortcuts__item" href="">
            <i class="zmdi zmdi-calendar"></i>
            <small class="">Calendar</small>
          </a>
        </div>
      </div>
    </li> -->

    <li class="hidden-sm-down">
      <a href="" data-sa-action="fullscreen"><i class="zmdi zmdi-fullscreen-alt"></i></a>
    </li>

    <!-- <li class="hidden-xs-down">
    	<a href="" class="top-nav__themes" data-sa-action="aside-open" data-sa-target=".themes"><i class="zmdi zmdi-palette"></i></a>
    </li> -->
	</ul>

  <div class="clock hidden-md-down">
    <div class="time">
      <span class="time__hours"></span>
      <span class="time__min"></span>
      <span class="time__sec"></span>
    </div>
  </div>
</header>

app/views/layouts/app/_sidebar.html.erb
<aside class="sidebar">
  <div class="scrollbar-inner">
    <% if current_admin %>
      <%= render "layouts/app/user_info", 
          user: current_admin, 
          logout_path: destroy_admin_session_path,
          is_admin: true %>
    <% else %>
      <%= render "layouts/app/user_info",
          user: current_p_participant, 
          logout_path: destroy_p_participant_session_path,
          is_admin: false %>
    <% end %>

    <ul class="navigation">
      <% if current_admin %>
        <li class="<%= active_class?(['dashboard'], [], false) %>">
          <%= link_to admin_authenticated_path do %>
            <i class="zmdi zmdi-home"></i> <%= t("l.dashboard") %>
          <% end %>
        </li>
        <% if policy(Event).index? %>
          <li class="<%= active_class?(['events', 'sessions'], [], false) %>">
            <%= link_to events_path do %>
              <i class="zmdi zmdi-calendar"></i> <%= t("l.events") %>
            <% end %>
          </li>
        <% end %>
        <% if policy(Survey).index? %>
          <li class="<%= active_class?(['surveys'], [], false) %>">
            <%= link_to surveys_path do %>
              <i class="zmdi zmdi-assignment"></i> <%= t("l.surveys") %>
            <% end %>
          </li>
        <% end %>
        <% if policy(FaqSet).index? %>
          <li class="<%= active_class?(['faq_sets'], [], false) %>">
            <%= link_to faq_sets_path do %>
              <i class="zmdi zmdi-pin-help"></i> <%= t("l.faqs") %>
            <% end %>
          </li>
        <% end %>
        <% if policy(Question).index? %>
          <li class="<%= active_class?(['questions'], [], false) %>">
            <%= link_to questions_path do %>
              <i class="zmdi zmdi-help"></i> <%= t("l.questions") %>
            <% end %>
          </li>
        <% end %>
        <% if policy(Admin).index? %>
          <li class="<%= active_class?(['admins'], [], false) %>">
            <%= link_to admins_path do %>
              <i class="zmdi zmdi-accounts"></i> <%= t("l.admin_users") %>
            <% end %>
          </li>
        <% end %>
        <!-- <li class="navigation__sub <%#= active_class?(['dashboard'], [], true) %>">
          <a href=""><i class="zmdi zmdi-view-week"></i> Variants</a>

          <ul>
            <li class="<%#= active_class?(['dashboard'], ['index'], false) %>">
              <%#= link_to t("l.dashboard"), admin_authenticated_path %>
            </li>
            <li class="<%#= active_class?(['dashboard'], ['index'], false) %>">
              <%#= link_to t("l.dashboard"), admin_authenticated_path %>
            </li>
            <li class="<%#= active_class?(['dashboard'], ['index'], false) %>">
              <%#= link_to t("l.dashboard"), admin_authenticated_path %>
            </li>
          </ul>
        </li> -->
      <% else %>
        <li class="<%= active_class?(['rooms'], [], false) %>">
          <%= link_to p_participant_authenticated_path do %>
            <i class="zmdi zmdi-cast"></i> <%= t("l.rooms") %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</aside>

app/views/layouts/app/_user_info.html.erb
<div class="user">
  <div class="user__info" data-toggle="dropdown">
    <!-- <img class="user__img" src="demo/img/profile-pics/8.jpg" alt=""> -->
    <div>
      <div class="user__name"><%= user.name %></div>
      <div class="user__email"><%= user.email %></div>
    </div>
  </div>

  <div class="dropdown-menu">
    <% if is_admin %>
      <%= link_to t("l.view_profile"), user, class: "dropdown-item" %>
      <%= link_to t("l.settings"), edit_admin_path(user), class: "dropdown-item" %>
    <% end %>
    <%= link_to t("l.logout"), logout_path, method: :delete, class: "dropdown-item" %>
  </div>
</div>