config/routes.rb
Rails.application.routes.draw do
	constraints subdomain: /^(www)$/ do
		scope '(:locale)', locale: /ms|en/ do
			mount ActionCable.server => 'cable'
			root 'home#index'
			namespace :p do
				# PARTICIPANT
				devise_for :participants, path: 'participant_auth', controllers: { 
					registrations: 'participant_auth/registrations',
					sessions: 'participant_auth/sessions'
				}
				authenticated :participant do 
					devise_scope :participant do 
						root to: 'rooms#index', as: 'participant_authenticated' 
					end
				end
				unauthenticated do
					devise_scope :participant do
						root to: 'home#index', as: 'participant_unauthenticated'
					end
				end
				post '/validate', to: 'home#validate_participant', as: 'validate_participant'
				resources :rooms, only: [:index, :show], param: :session_key do
					member do
						post :create_question
						patch :vote
						patch :poll
						post :submit_survey
					end
				end
				root 'rooms#index'
				# PARTICIPANT
			end
			# ADMIN
			scope :admin do
				devise_for :admins, path: 'admins', controllers: { 
					sessions: 'admins/sessions', 
					passwords: 'admins/passwords',
					confirmations: 'admins/confirmations',
					unlocks: 'admins/unlocks'
				}, path_names: {
					sign_in: 'login',
					sign_out: 'logout',
					password: 'secret',
					confirmation: 'verification',
					unlock: 'unblock',
					sign_up: 'logup'
				}
				authenticated :admin do 
					devise_scope :admin do 
						root to: 'dashboard#index', as: 'admin_authenticated' 
					end
				end
				unauthenticated do
					devise_scope :admin do
						root to: 'admins/sessions#new', as: 'admin_unauthenticated'
					end
				end
				resources :admins
				resources :surveys do
					member do
						get :settings
						get :search_question
						post :add_question
						post :create_question
						post :update_question_format
						delete :remove_question
					end
				end
				resources :faq_sets do
					member do
						get :settings
						get :search_question
						post :add_question
						post :create_question
						post :update_question_format
						delete :remove_question
					end
				end
  			resources :questions
				resources :events do
					member do
						get :review
						get :summary
						patch :react, constraints: CommitParamRouting.new(EventsController::SUBMIT), action: :submit
						patch :react, constraints: CommitParamRouting.new(EventsController::APPROVE), action: :approve
						patch :react, constraints: CommitParamRouting.new(EventsController::REJECT), action: :reject
						patch :react, constraints: CommitParamRouting.new(EventsController::CANCEL), action: :cancel
						post :send_invitation
					end
					resources :sessions do
						member do
							get :room
							get :pubroom
							get :settings
							post :add_attachment
							post :add_faq_set
							post :add_survey
							post :update_status
							post :add_poll_item
							post :update_question_status
							patch :import_participants
							delete :remove_attachment
							delete :remove_faq_set
							delete :remove_survey
							delete :remove_poll_item
							get :survey_responses
						end
						resources :polls, path: '/settings/polls', except: [:index, :show]
					end
				end

				#SEARCH
				match 'search' => 'dashboard#search', via: [:get, :post], as: 'search'
			end
			# ADMIN
		end
	end
end

app/models/survey.rb
class Survey < ApplicationRecord
	belongs_to :creator, class_name: 'Admin'
	has_many :survey_questions
	has_many :questions, through: :survey_questions
	has_many :session_surveys
	has_many :sessions, through: :session_surveys
  validates :title, presence: true

	def as_json(options = {})
		hash								= {}
		hash["id"]					= id
		hash["title"]				= title
		hash["description"]	= description
		hash["questions"]		= survey_questions.includes(question: [:creator]).order('created_at ASC').as_json
		hash["creator"]			= creator.name

		if options[:session_id]
      hash["checked"] = sessions.where(id: options[:session_id]).exists?
    end

		return hash
	end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_survey, only: [
    :show, 
    :edit, 
    :update, 
    :destroy, 
    :settings,
    :create_question,
    :add_question,
    :remove_question,
    :update_question_format
  ]
  include Pundit
  after_action :verify_authorized
  after_action :verify_policy_scoped

  def index
    @q = policy_scope(Survey).ransack(params[:q])
    @surveys = @q.result.order('created_at DESC')
    authorize @surveys

    respond_to do |format|
      format.html {
        @surveys = @surveys.page(params[:page]).per(10)
      }
      format.json {
        if params[:session_id].present?
          render json: @surveys.as_json(session_id: params[:session_id])
        end
      }
    end
  end

  def show
    authorize @survey
  end

  def settings
    authorize @survey
  end

  def new
    @survey = policy_scope(Survey).new
    
    if current_admin.huadmin?
      @survey = current_admin.created_surveys.new
    end

    authorize @survey
  end

  def edit
    authorize @survey
  end

  def create
    @survey = policy_scope(Survey).new(survey_params)
    
    if current_admin.huadmin?
      @survey = current_admin.created_surveys.new(survey_params)
    end

    authorize @survey

    if @survey.save
      redirect_to @survey, notice: t('msg.created')
    else
      render :new
    end
  end

  def update
    authorize @survey

    if @survey.update(survey_params)
      redirect_to @survey, notice: t('msg.updated')
    else
      render :edit
    end
  end

  def destroy
    authorize @survey
    @survey.destroy
    redirect_to surveys_url, notice: t('msg.destroyed')
  end

  def create_question
    @question         = @survey.questions.new(question_params)
    @question.creator = current_admin
    @question.origin  = :survey

    authorize @survey

    if @question.save
      @survey.survey_questions.create(question: @question)
      render json: @survey.survey_questions.find_by(question: @question).as_json
    else
      render json: @question.errors, status: :unprocessable_entity
    end
  end

  def add_question
    authorize @survey
    @survey_question = @survey.survey_questions.where(question_id: params[:question_id]).first_or_create
    render json: @survey_question.as_json
  end

  def remove_question
    authorize @survey
    @survey_questions = @survey.survey_questions.where(question_id: params[:question_id]).destroy_all
    head :no_content
  end

  def update_question_format
    authorize @survey
    @survey_question = @survey.survey_questions.where(id: params[:survey_question_id]).first
    @survey_question.update_attribute(:question_format, params[:question_format].to_sym)
    render json: @survey_question.as_json
  end

  private
    def set_survey
      @survey = policy_scope(Survey).find(params[:id])
    end

    def survey_params
      params.require(:survey).permit(policy(Survey).permitted_attributes)
    end

    def question_params
      params.require(:question).permit(:body)
    end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_form.html.erb
<%= simple_form_for(survey) do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <div class="mt-5 text-center">
    <%= f.button :submit, t('l.save'), class: "btn btn-light" %>
  </div>
<% end %>

app/views/surveys/_survey_details.html.erb
<%= content_for :actions do %>
  <div class="actions">
    <%= link_to "", surveys_path, class: "actions__item zmdi zmdi-arrow-left", data: tooltip_data(t("l.back")) %>
    <% if policy(survey).update? %>
      <%= link_to "", edit_survey_path(survey), class: "actions__item zmdi zmdi-edit", data: tooltip_data(t("l.edit")) %>
    <% end %>
    <% if act == 'show' && policy(survey).settings? %>
      <%= link_to "", settings_survey_path(survey), class: "actions__item zmdi zmdi-settings", data: tooltip_data(t("l.settings")) %>
    <% end %>
  </div>
<% end %>

<div class="card">
  <div class="card-body">
    <div class="row">
      <div class="col-md-6">
        <div class="row">
          <div class="col-md-12">
            <div class="form-group">
              <strong><%= t('l.title') %></strong><br>
              <%= survey.title %>
            </div>
          </div>
          <div class="col-md-12">
            <div class="form-group">
              <strong><%= t('l.creator') %></strong><br>
              <%= survey.creator.name %>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="row">
          <div class="col-md-12">
            <div class="form-group">
              <strong><%= t('l.description') %></strong><br>
              <%= survey.description %>
            </div>
          </div>
          <div class="col-md-12">
            <div class="form-group">
              <strong><%= t('l.created_at') %></strong><br>
              <%= survey.created_at.strftime("%d-%m-%Y") %>
            </div>
          </div>
        </div>
      </div>
      <% if survey.survey_questions.any? %>
        <div class="col-md-12">
          <h4>
            <%= t("l.questions") %>
          </h4>
          <div class="clearfix mb-3"></div>

          <div class="listview listview--bordered listview--hover">
            <% survey.survey_questions.includes(:question).each_with_index do |sq, i| %>
              <a class="listview__item" href="<%= question_path(sq.question) %>">
                <div class="listview__content">
                  <div class="listview__heading">
                    <%= i + 1 %>. <%= sq.question.body %>
                  </div>
                  <p><%= sq.question_format.humanize %></p>
                </div>
              </a>
            <% end %>
            <div class="clearfix mb-3"></div>
          </div>
        </div>
      <% end %>
    </div>
    <% if act == 'settings' %>
      <hr>
      <div class="row">
        <div class="col-md-12">
          <h4><%= t('l.questions') %></h4>

          <div id="survey_questions">
            <survey-questions :survey="<%= survey.as_json.to_json %>"></survey-questions>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/surveys/edit.html.erb
<%= page_title "#{t('l.surveys')} - #{t('l.edit')}" %>

<div class="content__inner">
  <div class="card">
    <div class="card-body">
			<%= render 'form', survey: @survey, act: 'edit' %>
		</div>
  </div>
</div>

<% content_for :actions do %>
	<div class="actions">
		<%= link_to "", surveys_path, class: "actions__item zmdi zmdi-arrow-left", data: tooltip_data(t('l.back'))  %>
		<%= link_to "", @survey, class: "actions__item zmdi zmdi-search-in-file", data: tooltip_data(t('l.view'))  %>
	</div>
<% end %>

app/views/surveys/index.html.erb
<%= page_title t("l.surveys") %>

<%= content_for :actions do %>
  <div class="actions">
    <% if policy(Survey).create? %>
      <%= link_to "", new_survey_path, class: "actions__item zmdi zmdi-plus", data: tooltip_data(t("l.add_new")) %>
    <% end %>
  </div>
<% end %>

<div class="table-responsive">
  <table class="table table-hover mb-3">
    <thead class="thead-default">
      <tr>
        <th>#</th>
        <th><%= t('l.title') %></th>
        <th><%= t('l.description') %></th>
        <th><%= t('l.creator') %></th>
        <th><%= t('l.created_at') %></th>
        <th width="5%"></th>
      </tr>
    </thead>

    <tbody>
      <% @surveys.each_with_index do |survey, i| %>
        <tr>
          <th scope="row"><%= i + 1 %></th>
          <td>
            <%= link_to survey do %>
              <%= survey.title %>
            <% end %>
          </td>
          <td><%= survey.description.truncate(50) %></td>
          <td><%= survey.creator.name %></td>
          <td><%= survey.created_at.strftime("%d-%m-%Y") %></td>
          <td>
            <div class="btn-group">
              <% if policy(survey).settings? %>
                <%= link_to t('l.settings'), settings_survey_path(survey), class: "btn btn-light btn-sm" %>
              <% end %>
              <% if policy(survey).update? %>
                <%= link_to t("l.edit"), edit_survey_path(survey), class: "btn btn-secondary btn-sm" %>
              <% end %>
              <% if policy(survey).destroy? %>
                <%= link_to t("l.delete"), survey, method: :delete, data: { confirm: t("msg.are_u_sure") }, class: "btn btn-danger btn-sm" %>
              <% end %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= paginate @surveys %>
</div>

app/views/surveys/new.html.erb
<%= page_title "#{t('l.surveys')} - #{t('l.add_new')}" %>

<div class="content__inner">
  <div class="card">
    <div class="card-body">
			<%= render 'form', survey: @survey, act: 'create' %>
		</div>
  </div>
</div>

<% content_for :actions do %>
	<div class="actions">
		<%= link_to "", surveys_path, class: "actions__item zmdi zmdi-arrow-left", data: tooltip_data(t("l.back")) %>
	</div>
<% end %>

app/views/surveys/settings.html.erb
<% content_for :vue  do %>
  <%= javascript_pack_tag 'survey_questions' %>
<% end %>

<%= page_title "#{t('l.surveys')} - #{@survey.title} - #{t('l.questions')}" %>

<%= render 'survey_details', survey: @survey, act: 'settings' %>

app/views/surveys/show.html.erb
<%= page_title "#{t('l.surveys')} - #{@survey.title}" %>

<%= render 'survey_details', survey: @survey, act: 'show' %>